# Generated by Django 4.2.1 on 2023-05-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='travel_website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
